### ISSUE TITLE
Issues with sound after recent update.

### ISSUE THREAD

**Issue by Omniphantasm** [Anveio/mturk-engine#21]
After the recent update I've noticed that I rarely get the dings anymore. Which I could live with but it seems like when the dings break the notifications also stop popping up in the corner as well.
 
Also when I do get the dings it seems like they're a different ding that is much quieter and *much* harder to hear over other noises for instance Netflix or my games.

Suggestion: At this point if possible I think it'd be best if you provide us with an easy way to select our own local sound file to use as a notification sound since not everybody is going to be happy with X sound or able to hear X sound.

* Mturk Engine version: Latest as of March 8th 2018
* Browser: Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by Anveio** [comment]
Thanks for posting this issue @Omniphantasm. I think this has something to do with the "Hide requesters with no Turkopticon score" option. See if temporarily disabling that resolves the issue of audio not playing while I work on a fix.

The new ding is quieter than the old one but maybe a higher volume setting can solve that problem for you. The new ding is hopefully a lot more tolerable at higher volumes.

I'd like to allow users to upload their own audio files at some point but there are a few challenges there and it's lower on my priority list than some other features I'm currently working on.

**Comment by Omniphantasm** [comment]
I’ve never used the hide requesters option but I checked and it was still off so doesn’t seem to be that. 

As for the volume I’ve got both chrome maxed out on windows and the ding volume slider maxed out. It’s still getting overpowered by other audio I’ve got going on which sucks but I’ll likely learn to deal with it until there’s a better option.

**Comment by wapem** [comment]
I concur .. the new dings is way to quiet ! i can barely hear it with headphones on with no other sound in background at maximum volume, imagine if watching a movie or watching youtube etc .. put the old sound back ! seriously ! who think the old sound is too loud they can lower their volume .. this new sound is pathetic !

**Comment by Anveio** [comment]
Thanks for the feedback @wapem and @Omniphantasm I've released a small update that significantly increases the volume of both the new search result audio and successful watcher accept audio. See if it works for you after updating.

I don't think it's a good idea to revert to the old 'coins' sound because I received feedback that it became very unpleasant past 50% volume.

**Comment by Omniphantasm** [comment]
Thanks much!

**Comment by wapem** [comment]
@Anveio Still not enough , the sound is still too soft , please find a proper sound or else this script will become obsolete and that would be a shame because is the best script as of now.

**Comment by Anveio** [comment]
Sorry @wapem but I'm not comfortable making the current sound any louder, nor do I think reverting to the old sound is a good idea. If you have suggestions for other sounds to use I'm open to hearing them. 

Alternatively, because Mturk Engine is open source, you can follow the steps in the [developer readme](https://github.com/Anveio/mturk-engine/blob/master/src/constants/audio.ts) to create your own version of the script and change [these lines](https://github.com/Anveio/mturk-engine/blob/master/src/constants/audio.ts) to whatever sound you like.

Thanks for the kind words.

**Comment by wapem** [comment]
@Anveio  yes i will try add my own sound , but the real problem is the sound not playing at all when having  tasks, desktop notifications are dead also , everything was working fine until the 1.6 version , now is just hit and miss , sometimes works most of the times doesn't. Any fix for that ?

**Comment by Anveio** [comment]
@wapem I'm not able to reproduce the bug of desktop notifications intermittently working. If you'd like to help me out, create a new issue with steps to reproduce it.

I'm locking this conversation for now. I'll update when I have a fix for the audio issue.

**Comment by Anveio** [comment]
I've released a small patch (1.6.2) that hopefully fixes this problem. Update the script and let me know if you still run in to the issue. I'll close the issue for now but I'll re-open it if the update hasn't fully resolved it.

This turned out to be an interesting bug to track down. An under-the-hood change I made in 1.6.0 was to move the audio and notification layer components into the search table component in an effort to clean up the top level of the component tree. This was actually a mistake, because the Search Table would render the empty state instead of the notification and audio components when there were no results to show after filtering out by blocklist and T.O. This meant the audio and notification components unmounted completely and caused them to 'forget' what the last results were and the comparison to decide whether or not to show a notification or play audio would return false when it should return true.

This bug was most pronounced when using the "Hide requesters with no T.O." option, which initially led me down the wrong path, but it also occurred if your search intermittently returned 0 results after filtering, which occurred for users with large blocklists and high minimum T.O.
